name: canopy
channels:
  - conda-forge
  - openalea3
  # - fredboudon
dependencies:
  # - embreex  # Not available on conda-forge, can be removed once hothouse is published
  # - hothouse
  - ffmpeg
  - imageio
  - matplotlib
  - numpy  # Compatibility with pandas
  - openalea.lpy  # Current conda install from fredboudon fails as of 9/11/2025
  - pandas
  - pvlib
  - python
  - pyshp
  - pytest
  - pyyaml
  - scipy
  - yggdrasil-rapidjson
  # - yggdrasil-python-rapidjson  # Waiting on conda-forge feedstock
  # - yggdrasil
  # yggdrasil dependencies
  - czmq
  # - ePhotosynthesis_C  # Once this is released
  - sundials>=5.7.0  # For building ePhotosynthesis_C