# Dependencies required to build pyembree (and embree 2.*.*)
name: canopy
channels:
  - conda-forge
dependencies:
  - cmake
  - cython
  # - freeglut  # Not required (or available) on mac as glut is installed
  - setuptools
  - setuptools_scm
  - tbb
  - tbb-devel
