name: canopy
channels:
  - conda-forge
  - fredboudon
dependencies:
  - ffmpeg
  - imageio
  - matplotlib
  - numpy < 2  # Compatibility with pandas
  - openalea.lpy
  - pandas
  - pvlib
  - python
  - pyshp
  - pytest
  - scipy
  - yggdrasil
