name: Build, test and upload to PyPI

on:
  push:
    branches-ignore:
     - gh-pages
    tags:
     - '*'
  schedule:
    - cron: 0 10 * * 1  # 3AM PST

env:
  PYTHONVERSION_STD: "3.12"

jobs:
  tests:
    name: All tests, on current Python
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]  # ["3.10", 3.11, 3.12, 3.13]  # , 3.14]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      # - name: (WINDOWS,CONDA) Set up MSVC Compiler
      #   uses: ilammy/msvc-dev-cmd@v1
      #   if: matrix.os == 'windows-latest'
      - name: (CONDA) Set up miniconda base environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: canopy
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: msys,conda-forge,openalea3
          channel-priority: strict
          environment-file: environment.yml

      # Build & install dependencies
      - name: Install yggdrasil-python-rapidjson via pip until conda-forge feedstock available
        run: |
          pip install yggdrasil-python-rapidjson
      # - name: Install embree & hothouse build dependencies
      #   run: |
      #     conda env update -n canopy --file environment_raytrace.yml
      # - name: Install yggdrasil
      #   run: |
      #     cd ..
      #     ./canopy_factory/build_yggdrasil.sh
      # - name: Install ePhotosynthesis_C
      #   run: |
      #     cd ..
      #     ./canopy_factory/build_ePhotosynthesis_C.sh
      # - name: Install lpy
      #   run: |
      #     cd ..
      #     ./canopy_factory/build_lpy.sh
      # - name: Install embree
      #   run: |
      #     cd ..
      #     ./canopy_factory/build_embree.sh
      # - name: Install pyembree
      #   run: |
      #     cd ..
      #     ./canopy_factory/build_pyembree.sh
      - name: Install hothouse
        run: |
          cd ..
          ./canopy_factory/build_hothouse.sh

      - name: Install canopy_factory
        run: |
          pip install -v '.[dev]'

      - name: Show installed packages
        run: |
          conda list

      - name: Check syntax
        run: |
          flake8 canopy_factory

      - name: Test CLI
        run: |
          python -m canopy_factory -h

      - name: Tests
        run: |
          pytest -sv tests

      - name: Doctests
        run: |
          make -C docs doctest -e PYTHON=$(which python3)

  docs:
    name: Build the Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    # - name: Get tags required by setuptools_scm to generate version
    #   run: |
    #     git fetch --prune --unshallow
    #     git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up miniconda environment w/ dependencies
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: canopy
        auto-update-conda: true
        python-version: ${{ env.PYTHONVERSION_STD }}
        channels: msys,conda-forge,fredboudon
        channel-priority: strict
        environment-file: environment.yml
    - name: Install yggdrasil-python-rapidjson via pip until conda-forge feedstock available
      run: |
        pip install yggdrasil-python-rapidjson
    # - name: Install embree & hothouse build dependencies
    #   run: |
    #     conda env update -n canopy --file environment_raytrace.yml
    - name: Install hothouse
      run: |
        cd ..
        ./canopy_factory/build_hothouse.sh
    - name: Install canopy_factory
      run: |
        pip install -v '.[dev]'
    - name: Build the docs
      run: |
        cd docs
        make autodoc
        cd ../
    - name: Publish docs to Github pages
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/build/html/

  build_sdist:
    name: Build sdist & wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHONVERSION_STD }}

      - name: Install pypa/build
        run: python -m pip install build
      - name: Build a binary wheel and a source tarball
        run: python -m build  # --sdist
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: sdist
          path: |
            dist/*.whl
            dist/*.tar.gz

  # build_wheels:
  #   name: Build wheels on ${{matrix.arch}} for ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest, macos-15-intel]
  #       arch: [auto]
  #     fail-fast: false
            
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v6

  #     - name: Install Python
  #       uses: actions/setup-python@v6
  #       with:
  #         python-version: ${{ env.PYTHONVERSION_STD }}

  #     - name: Install cibuildwheel
  #       run: python -m pip install cibuildwheel==3.4.0

  #     - name: Build wheels
  #       run: python -m cibuildwheel --output-dir wheelhouse
  #       env:
  #         CIBW_ARCHS_LINUX: ${{ matrix.arch }}
  #         CIBW_ARCHS_MACOS: ${{ matrix.arch }}
  #         CIBW_ENABLE: cpython-prerelease

  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v6
  #       with:
  #         name: wheels-for-${{ matrix.os }}-${{ matrix.arch }}
  #         path: ./wheelhouse/*.whl

  upload_wheels:
    name: Upload wheels to PyPI
    needs: [build_sdist]  # , build_wheels]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    # Upload only for release
    if: github.event_name == 'release'

    # Upload to PyPI on every tag starting with 'v'
    # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')

    steps:
      # - uses: actions/download-artifact@v6
      #   with:
      #     path: dist
      #     pattern: wheels-for-*
      #     merge-multiple: true
      - uses: actions/download-artifact@v6
        with:
          path: dist
          pattern: sdist
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
